### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by jnadeau1976** [stayradiated/hifi.kitchen#10]
I have a lot of error "not found" during yarn install   .

Jonathan

**Comment by stayradiated** [comment]
Could you please include an error log, or specify which packages can't be found?

**Comment by stayradiated** [comment]
Actually, I'm pretty sure it's a bunch of namespaced packages I've forgotten to make public. Have another go at installing it.

**Comment by jnadeau1976** [comment]
it works perfectly now !  thanks

continue your good works !

Jonathan

2017-04-05 16:55 GMT-04:00 George Czabania <notifications@github.com>:
