### ISSUE TITLE
change IP

### ISSUE THREAD

**Issue by peva3** [stayradiated/hifi.kitchen#24]
Hey, how do I go about changing the site from localhost to any other IP/binding? Like 0.0.0.0 for instance.

**Comment by stayradiated** [comment]
I'm using create-react-app to run the dev server. You can set the `HOST` environment variable to change the binding.

```
HOST=192.168.0.100 yarn start
```

Just out of interest, why would you need to do this?

**Comment by peva3** [comment]
So when I started it, going to 192.168.1.XXX:3000/library doesnt work, its just not connecting. So I was assuming that its binding to localhost and not accepting anything else.

**Comment by stayradiated** [comment]
Is it working for you now?
