### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by leonardodino** [stayradiated/hifi.kitchen#27]
Hi! Awesome project!

I'm interested on forking this over to a `react-native` mobile app.

I have no financial interests. I just want to make a good open-source plex music mobile app, as the official one is paid, and kinda bloated for audio playback.

Please, consider adding a license to it! (:

**Comment by stayradiated** [comment]
Thanks :)

I've added the MIT license to this project.

My original idea was build a react-native mobile app, so I will be very interested to see how your project goes. I decided to build this web app instead, because I wanted to learn more about how the plex API works first.
